name: nb
base: core20
version: '6.11.2'
summary: CLI and local web plain text note‑taking, bookmarking, and archiving.
description: |
  CLI and local web plain text note‑taking, bookmarking, and archiving with
  linking, tagging, filtering, search, Git versioning & syncing,
  Pandoc conversion, + more, in a single portable script.

grade: stable
confinement: devmode # use 'strict' once you have the right plugs and slots

icon: docs/images/nb.png

apps:
  nb:
    command: bin/nb

parts:
  nb:
    plugin: dump
    source: .
    organize:
      nb: bin/

  dependencies:
    plugin: nil
    stage-packages:
      - bats
      - ncat
      - pandoc
